services:
  app:
    image: ghcr.io/${REPO_NAME}:qa
    container_name: socomarca_app_qa
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./phpcustom.ini:/usr/local/etc/php/conf.d/custom.ini

    depends_on:
      - db

    networks:
      - traefik-public
      - internal

  nginx:
    image: nginx:alpine
    container_name: socomarca_nginx_qa
    restart: unless-stopped

    volumes:
      - .:/var/www/html
      - ./nginx:/etc/nginx/conf.d

    depends_on:
      - app

    networks:
      - traefik-public
      - internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socomarca.rule=Host(`qa-api.appsocomarca.cl`)"
      - "traefik.http.routers.socomarca.entrypoints=websecure"
      - "traefik.http.routers.socomarca.tls.certresolver=myresolver"
      - "traefik.http.services.socomarca.loadbalancer.server.port=80"
      
  worker:
    image: ghcr.io/${REPO_NAME}:qa
    container_name: socomarca_worker_qa
    restart: unless-stopped

    command: php artisan queue:work --tries=3 --timeout=90

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - internal

volumes:
  db_data:

networks:
  traefik-public:
    external: true

  internal:
    driver: bridge
