services:
  workcontainer:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: socomarca_php
    restart: unless-stopped
    user: developer:developer
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html:cached
      - ./phpcustom.ini:/usr/local/etc/php/conf.d/custom.ini
    networks:
      - socomarca
    depends_on:
      - db
    expose:
      - 9000
    environment:
      - PHP_UPLOAD_MAX_FILESIZE=100M
      - PHP_POST_MAX_SIZE=100M
  web:
    image: nginx:alpine
    container_name: socomarca_web
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - socomarca
    depends_on:
      - workcontainer

  db:
    image: postgres
    restart: unless-stopped
    shm_size: 128mb
    volumes:
     - type: tmpfs
       target: /dev/shm
       tmpfs:
         size: 134217728 # 128MB
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    ports:
      - "5432:5432"
    networks:
      - socomarca
  localstack:
    image: localstack/localstack
    container_name: socomarca_localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
    networks:
      - socomarca
volumes:
  socomarca_data:
    name: socomarca_data
  socomarca_s3_data:
    name: socomarca_s3_data

networks:
  socomarca:
