services:
  app:
    image: ghcr.io/${REPO_NAME}:qa
    container_name: socomarca_app_qa
    restart: unless-stopped

    env_file:
      - .env

    volumes:
      - ./phpcustom.ini:/usr/local/etc/php/conf.d/custom.ini

    depends_on:
      - db

    networks:
      - traefik-public
      - internal

  nginx:
    image: nginx:alpine
    container_name: socomarca_nginx_qa
    restart: unless-stopped

    volumes:
      - ./nginx:/etc/nginx/conf.d

    depends_on:
      - app

    networks:
      - traefik-public
      - internal

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.socomarca.rule=Host(`qa.tudominio.com`)"
      - "traefik.http.routers.socomarca.entrypoints=websecure"
      - "traefik.http.routers.socomarca.tls.certresolver=myresolver"
      - "traefik.http.services.socomarca.loadbalancer.server.port=80"

  db:
    image: postgres:15
    container_name: socomarca_db_qa
    restart: unless-stopped

    env_file:
      - .env

    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}

    volumes:
      - db_data:/var/lib/postgresql/data

    networks:
      - internal

  localstack:
    image: localstack/localstack
    container_name: socomarca_localstack
    restart: unless-stopped

    ports:
      - "4566:4566"

    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1

    networks:
      - internal

  worker:
    image: ghcr.io/${REPO_NAME}:qa
    container_name: socomarca_worker_qa
    restart: unless-stopped

    command: php artisan queue:work --tries=3 --timeout=90

    env_file:
      - .env

    depends_on:
      - db

    networks:
      - internal

volumes:
  db_data:

networks:
  traefik-public:
    external: true

  internal:
    driver: bridge
