[supervisord]
nodaemon=true
user=root
logfile=/dev/stdout
logfile_maxbytes=0


[program:laravel-scheduler]
command=php /app/artisan schedule:work
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:laravel-worker-default]
command=php artisan queue:work --queue=default --tries=3 --timeout=60
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:laravel-worker-email]
command=php artisan queue:work --queue=email --tries=3 --timeout=60
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:laravel-worker-sync-products]
command=php artisan queue:work --queue=random-sync-products --tries=1 --timeout=900 --max-jobs=20
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:laravel-worker-sync-users]
command=php artisan queue:work --queue=random-sync-users --tries=1 --timeout=900 --max-jobs=20
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0

[program:laravel-worker-sync-credit]
command=php artisan queue:work --queue=random-sync-credit --tries=1 --timeout=300 --max-jobs=20
autostart=true
autorestart=true
numprocs=1
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
