<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

return new class extends Migration
{
    /**
     * Normalize existing emails (lowercase, trimmed) and remove the temporary
     * emails generated by the random:fix-users command (temp_{KOEN}@socomarca.temp).
     */
    public function up(): void
    {
        DB::table('users')
            ->whereNotNull('email')
            ->update(['email' => DB::raw("NULLIF(lower(trim(email)), '')")]);

        DB::table('users')
            ->where('email', 'like', 'temp\_%@socomarca.temp')
            ->update(['email' => null]);
    }

    /**
     * The original values cannot be restored.
     */
    public function down(): void
    {
        //
    }
};
